### ISSUE TITLE
consider moving code into mimesis.pytest_plugin

### ISSUE THREAD

**Issue by graingert** [mimesis-lab/pytest-mimesis#81]
then this project can be a thin shim that just registers the entry point:

```toml
[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "pytest_mimesis"
dist-name = "pytest-mimesis"
author = "..."
author-email = "..."
home-page = "https://github.com/lk-geimfari/mimesis/tree/master/mimesis/pytest_plugin.py"
license = "..."
classifiers = ["..."]
requires = ["mimesis >= 4.2.0"]

[tool.flit.entrypoints.pytest11]
mimesis = "mimesis.pytest_plugin"
```

this is the approach used by pytest-celery:

* https://docs.celeryproject.org/en/stable/userguide/testing.html#enabling
* https://github.com/celery/pytest-celery/blob/master/pyproject.toml#L15-L16
